### ISSUE TITLE
User Journey: As a user, I want to learn about community-centered strategic planning and resource management in an engaging way

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#14]
- [x] I want background information on the context of the game/project #16 
    - [x] I want to be shown information about what a hub is
- [x] I want clear instructions on how to play the game #17
- [x] I want the choice to play with a given scenerio OR with my own context #18
- [x] Upon choosing a scenario, I want to  be given a scenario, user profile, and challenges with which to continue the game #19
- [x] I want to be able to make a selection of methods to fulfill the challenges provided by my personas / context #20
    - [x] I want to be shown information about each method (category, resource cost, link to more information) #20
    - [x] I want to have an indication of how many resources I might have available to me and how that might affect my choice of methods #20
- [ ] I want to be provided with a framework of thought in which I can begin to prioritize my chosen methods #21
- [x] I want to be provided with a framework in which I can begin to imagine timelining the implementation of my chosen methods #24
- [ ] I want to receive feedback on the effectiveness of my choices of methods #24
- [ ] I want to receive feedback on the resources required to take advantage of my choices of methods #24
- [x] I want to be given access to links to guides about how to use my chosen methods #24
