### ISSUE TITLE
Technical user stories

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#15]
### Pages
- [x] I want a landing page #25 
- [x] I want error pages (404, 500) #26
- [x] I want a key terms page #27

### Features
- [x] I want to be able to change my choices #20 
- [x] I want a warning page reminding me that I have not spent all my resources before moving to the next step #71 

### Components
- [x] I want a header component with logo and hamburger menu, and title #28
- [x] I want a hamburger menu component #29
- [x] I want a footer component with back and forward component buttons #30
- [x] I want a banner component to reuse on landing and alert pages #31 
- [x] I want a carousel component for method cards

**Comment by Oliversw** [comment]
I think it might be worth breaking everything down technically in this issue, even if it comes up in the user journey issues. What else do we want to break into components @ali-7 @hshahwan @teenie-quaggard ?
