### ISSUE TITLE
Method selection page

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#20]
### User Story
As a user, I want to be able to make a selection of methods to fulfill the challenges provided by my personas / context

** I think this is a complicated issue that will have to be split into separate issues as we figure out exactly how we want to implement everything.

### Acceptance Criteria
- [x] contains header
- [x] contains title
- [x] contains method selection section
   - [x] section displays as carousel on mobile
   - [x] methods pulled from JSON file
   - [x] methods displayed as cards
      - [x] option to display more information
- [x] contains option to select this method
- [x] contains selected methods section
   - [x] displays as carousel
   - [x] option to delete selected methods
- [x] contains "Resources remaining" counter
- [x] contains "back", "next", and "review scenario/challenges buttons in footer
   - [x] "Review scenario/challenges" button attached to modal pop up?

### Screenshots
![Screen Shot 2019-04-15 at 2 23 48 PM](https://user-images.githubusercontent.com/9094166/56136170-273dd500-5f8a-11e9-9254-afb9f5ffb96a.png)
