### ISSUE TITLE
Priorities and timeline selection

### ISSUE THREAD

**Issue by Oliversw** [founders-programme-2/commons#21]
### User Story
As a user, I want to be provided with a framework of thought in which I can begin to prioritize my chosen methods

### Acceptance Criteria
- [x] priorities and timeline about page
   - [x] contains header
   - [x] contains title
   - [x] contains "back" and "next" buttons in footer

- [x] priorities and timeline selection page
   - [x] contains header
   - [x] contains title
   - [x] contains carousel with selected methods
   - [x] contains priority selection section
   - [x] contains timeline implementation section
   - [x] displays categories that the method falls into
   - [x] contains "back" and "next" buttons in footer

### Screenshots
![Screen Shot 2019-04-15 at 2 32 10 PM](https://user-images.githubusercontent.com/9094166/56136769-530d8a80-5f8b-11e9-8840-00ce97765158.png)
